# Node docker image on which this would be run
image: node:14

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy_development

# Job 1:
Build:
  stage: build
  script:
    - yarn

# Job 2:
# Deploy to staging
Deploy:
  image: ruby:latest
  only:
    - develop
  stage: deploy_development
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY