# Node docker image on which this would be run
image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy_release
  - deploy_feature
  - deploy_production

# Job 1:
Test:
  stage: test
  cache:
    key: modules
    policy: push
    paths:
      - node_modules/
  before_script:
    - yarn install
  script:
    - yarn test

# Job 2:
# Deploy to staging
Release: &deploy
  image: ruby:latest
  stage: deploy_release
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=release-bora --api-key=$HEROKU_API_KEY
  only:
    - /^release\/.*$/

Feature:
  <<: *deploy
  stage: deploy_feature
  script:
    - dpl --provider=heroku --app=feature-bora --api-key=$HEROKU_API_KEY
  only:
    - /^feature\/.*$/

Production:
  <<: *deploy
  stage: deploy_production
  script:
    - dpl --provider=heroku --app=bora-app --api-key=$HEROKU_API_KEY
  only:
    - master
